# Generated by Django 5.0 on 2024-01-02 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Производитель')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=300, verbose_name='Страна')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('street', models.CharField(max_length=300, verbose_name='Улица')),
                ('house', models.CharField(max_length=250, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Производитель')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('type', models.CharField(choices=[('торговая сеть', 'торговая сеть'), ('ИП', 'ИП')], verbose_name='Тип поставщика')),
                ('country', models.CharField(max_length=300, verbose_name='Страна')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('street', models.CharField(max_length=300, verbose_name='Улица')),
                ('house', models.CharField(max_length=250, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producer', verbose_name='Производитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.commodity', verbose_name='Товар')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_supplier', to='product.supplier', verbose_name='Поставщик')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_recipient', to='product.supplier', verbose_name='Получатель поставки')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
            },
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
